name: Sync to S3 [team-won-2-dags-bucket]

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때, 워크플로우 실행 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Github Secrets
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Github Secrets
        aws-region: ap-northeast-2  # AWS 서울 리전

    - name: Sync to S3
      run: |
        aws s3 sync . s3://team-won-2-dags-bucket --exclude ".git/*" --exclude ".github/*"
